//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostManBoxes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class boxes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public boxes()
        {
            this.couriers = new HashSet<couriers>();
        }
    
        public long id { get; set; }
        public string customer_key { get; set; }
        public string pack_number { get; set; }
        public short dimensions { get; set; }
        public decimal weight { get; set; }
        public decimal to_pay { get; set; }
        public long destination_id { get; set; }
        public int current_check_point { get; set; }
        public byte delivery_status { get; set; }
    
        public virtual check_points check_points { get; set; }
        public virtual destinations destinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<couriers> couriers { get; set; }
    }
}
