//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostManBoxes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class couriers
    {
        public long id { get; set; }
        public int courier_id { get; set; }
        public long pack_id { get; set; }
        public Nullable<bool> is_available { get; set; }
    
        public virtual boxes boxes { get; set; }
    }
}
