//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostManBoxes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class destinations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public destinations()
        {
            this.boxes = new HashSet<boxes>();
        }
    
        public long id { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string post_code { get; set; }
        public string street { get; set; }
        public string house_number { get; set; }
        public string apartment_number { get; set; }
        public string recipient_name { get; set; }
        public string recipient_surname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boxes> boxes { get; set; }
    }
}
