//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostManBoxes.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class postman_pack_dbEntities : DbContext
    {
        public postman_pack_dbEntities()
            : base("name=postman_pack_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boxes> boxes { get; set; }
        public virtual DbSet<check_points> check_points { get; set; }
        public virtual DbSet<couriers> couriers { get; set; }
        public virtual DbSet<destinations> destinations { get; set; }
    }
}
